<?php include('include/header.php'); ?>
    </header>
    <!--==============================content=================================-->
    <div id="content">
      <div class="container">
        <div class="row">
          <div class="span4 float2">
        	<h3>terms of use</h3>
          	<p><strong class="text-info">Mauris volutpat nunc quis tempus</strong><br>
Nullam convallis; justo a vestibulum interdum, ipsum mauris lobortis urna, in fringilla elit erat at est. Nullam erat risus, volutpat quis porttitor eget, egestmauris eros non arcu. Aenean felis augue, dignissim in tempusas nodio. Aliquam erat volutpat. Proin eu purus sapien, eu accumsan dolor.</p> 
			<p><strong class="text-info">Curabitur lacinia tristique imperdiet</strong><br>
Nunc iaculis ligula eget massa dictum quis porttitor orci elementum! In lobortis consectetur elit sed fringilla? Aliquam malesuada urna eu dolor volutpat lobortis! Curabitur pellentesque, turpis sit amet iaculis condimentum, urna mi aliquet turpis, itae pharetra  eget, cursus sit amet sem? </p> 
			<p><strong class="text-info">Vestibulum interdum ipsum mauris lobortis urna</strong><br>
Cras vehicula vehicula nunc id fringilla? Nulla vestibulum condimentum felis, in viverra erat vehicula sed. Phasellus hendrerit dapibus libero, non malesuada nunc consectetur sed. Vestibulum volutpat suscipit sem, nec bibendum massa malesuada eget. Donec ultricies mattis mauris in bibendum. </p> 
			<strong class="text-info">Vivamus eu enim a orci accumsan tincidunt ut</strong><br>
Vivamus sollicitudin venenatis metus; a ullamcorper tortor 
dignissim a. Curabitur non orci sit amet magna scelerisque volutpat. Mauris ipsum metus, molestie vel pellentesque eget, vehicula eu arcu. Integer commodo dui dui, vel rhoncus felis! Duis at tempor massa. Nam quis dolor massa. 
          </div>  
          <div class="span8 float">
        	<h3>Privacy Policy</h3>
            <p class="lead">Aliquam erat volutpat Proin eu purus sapien eu accumsan dolor</p>
<p>Suspendisse commodo tempor sagittis! In justo est, sollicitudin eu scelerisque pretium, placerat eget elit. Praesent faucibus rutrum odio at rhoncus. Pellentesque vitae tortor id neque fermentum pretium. Maecenas ac lacus ut neque rhoncus laoreet sed id tellus. Donec justo tellus, tincidunt vitae pellentesque nec, pharetra a orci. Praesent nunc nunc, egestas eget elementum sed; rutrum eget metus! Vestibulum congue congue dui ut porta. Aenean laoreet viverra turpis, a commodo purus eleifend a. Nam lacus dui; egestas ut aliquam nec, eleifend sit amet est. Nam justo elit, dictum id tempus a, ultricies tempus lacus. Nunc purus nibh; eleifend eget facilisis ac, sagittis non tortor. Vivamus eu enim a orci accumsan tincidunt ut ut elit. Vestibulum nisi orci, rutrum ac auctor non.</p>
<p>Sed vehicula sem et arcu tincidunt accumsan. In non pellentesque ipsum. Curabitur facilisis pellentesque pharetra. Donec justo urna, malesuada a viverra ac, pellentesque vitae nunc. Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. Quisque mauris risus, gravida a molestie eu, dictum ac augue. Integer sodales tempor lectus; sit amet dictum metus pharetra nec. Fusce bibendum dapibus pretium. Nunc eu sem vitae lacus laoreet elementum. Nulla facilisi. Phasellus ullamcorper elementum est, id pretium turpis bibendum vel. Aliquam a odio arcu. Morbi a dignissim nisl? Aenean aliquet magna in nulla congue vehicula. </p> 
			<p class="lead">sapien eu accumsan dolor Nunc iaculis ligula eget massa dictum </p>
<p>Nunc purus nibh; eleifend eget facilisis ac, sagittis non tortor. Vivamus eu enim a orci accumsan tincidunt ut ut elit. Vestibulum nisi orci, rutrum ac auctor non, viverra et magna? Sed vehicula sem et arcu tincidunt accumsan. In non pellentesque ipsum. Curabitur facilisis pellentesque pharetra. Donec justo urna, malesuada a viverra ac, pellentesque vitae nunc. Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. Quisque mauris risus, gravida a molestie eu, dictum ac augue. Integer sodales tempor lectus; sit amet dictum metus pharetra nec. Fusce bibendum dapibus pretium. </p>
<p>Nunc eu sem vitae lacus laoreet elementum. Nulla facilisi. Phasellus ullamcorper elementum est, id pretium turpis bibendum vel. Aliquam a odio arcu. Morbi a dignissim nisl? Aenean aliquet magna in nulla congue vehicula. Morbi dignissim tristique turpis sed sodales. In tincidunt dapibus semper. Nullam non orci eu massa tempus aliquam! Quisque placerat metus at neque aliquam sit amet iaculis lacus iaculis. Etiam ultrices condimentum justo eu viverra. Curabitur lacinia tristique imperdiet. Aenean bibendum vehicula diam nec placerat. Donec lectus leo, consequat sit amet viverra et, lacinia eu lectus! Nullam convallis; justo a vestibulum interdum, ipsum mauris lobortis urna, in fringilla elit erat at est. Nullam erat risus, volutpat quis porttitor eget, egestas n odio.</p> 
<p class="lead">Morbi dignissim tristique turpis sed sodales In tincidunt dapibus semper</p>
<p>Curabitur facilisis pellentesque pharetra. Donec justo urna, malesuada a viverra ac, pellentesque vitae nunc. Aenean ac leo eget nunc fringilla fringilla a non nulla! Nunc orci mi, venenatis quis ultrices vitae, congue non nibh. Nulla bibendum, justo eget ultrices vestibulum, erat tortor venenatis risus, sit amet cursus dui augue a arcu. Quisque mauris risus, gravida a molestie eu, dictum ac augue. Integer sodales tempor lectus; sit amet dictum metus pharetra nec. Fusce bibendum dapibus pretium. Nunc eu sem vitae lacus laoreet elementum. Nulla facilisi. Phasellus ullamcorper elementum est, id pretium turpis bibendum vel. Aliquam a odio arcu. Morbi a dignissim nisl? Aenean aliquet magna in nulla congue vehicula. Morbi dignissim tristique turpis sed sodales. </p>
<p>In tincidunt dapibus semper. Nullam non orci eu massa tempus aliquam! Quisque placerat metus at neque aliquam sit amet iaculis lacus iaculis. Etiam ultrices condimentum justo eu viverra. Curabitur lacinia tristique imperdiet. Aenean bibendum vehicula diam nec placerat. Donec lectus leo, consequat sit amet viverra et, lacinia eu lectus! Nullam convallis; justo a vestibulum interdum, ipsum mauris lobortis urna, in fringilla elit erat at est. Nullam erat risus, volutpat quis porttitor eget, egestas n odio. Aliquam erat volutpat. Proin eu purus sapien, eu accumsan dolor. Nunc iaculis ligula eget massa dictum quis porttitor orci elementum! In lobortis consectetur elit sed fringilla? Aliquam malesuada urna eu dolor volutpat lobortis! Curabitur pellentesque, turpis sit amet.</p> 
<a href="#">privacy@demolink.org</a>
          </div>  
        </div>
      </div>
  </div>     
<!--==============================footer=================================-->
<?php include('include/footer.html'); ?>